### ISSUE TITLE
Element implicitly has an 'any' type because type 'Response' has no index signature

### ISSUE THREAD

**Issue by jholovacs** [leonardobazico/angular2-jwt-refresh#14]
in my `app.module.browser.ts` file, I added the following imports as documented:
```
import { AuthConfig } from 'angular2-jwt';
import { JwtConfigService, JwtHttp } from 'angular2-jwt-refresh';
```

in the @NgModule decorator, I added the provider as documented:
```
    providers: [
        ...
        {
            provide: JwtHttp,
            useFactory: getJwtHttp,
            deps: [Http, RequestOptions]
        },

```
Then I added the function export as documented:

```
export function getJwtHttp(http: Http, options: RequestOptions) {
    let jwtOptions = {
        endPoint: '/api/auth/refresh',
        // optional
        payload: { type: 'refresh' },
        beforeSeconds: 600, // refresh token before 10 min
        tokenName: 'refresh_token',
        refreshTokenGetter: (() => localStorage.getItem('refresh_token')),
        tokenSetter: ((res: Response): boolean | Promise<void> => {
            res = res.json();

            if (!(res['id_token']  || !res['refresh_token']) {
                localStorage.removeItem('id_token');
                localStorage.removeItem('refresh_token');

                return false;
            }

            localStorage.setItem('id_token', res['id_token']);
            localStorage.setItem('refresh_token', res['refresh_token']);

            return true;
        })
    };
    let authConfig = new AuthConfig({
        noJwtError: true,
        globalHeaders: [{ 'Accept': 'application/json' }],
        tokenGetter: (() => localStorage.getItem('id_token')),
    });

    return new JwtHttp(
        new JwtConfigService(jwtOptions, authConfig),
        http,
        options
    );
}
```

However, right off the bat, I'm getting errors.

on the `if (!(res['id_token']  || !res['refresh_token']) {` line, I get the message "TS7017: Element implicitly has an 'any' type because type 'Response' has no index signature."

on the `let authConfig = new AuthConfig({` line, I get:

> TS2345: Argument of type '{ noJwtError: true; globalHeaders: { 'Accept': string; }[]; tokenGetter: () => string | null; }' is not assignable to parameter of type 'IAuthConfigOptional | undefined'.
>       Type '{ noJwtError: true; globalHeaders: { 'Accept': string; }[]; tokenGetter: () => string | null; }' is not assignable to type 'IAuthConfigOptional'.
>         Types of property 'tokenGetter' are incompatible.
>           Type '() => string | null' is not assignable to type '(() => string | Promise<string>) | undefined'.
>             Type '() => string | null' is not assignable to type '() => string | Promise<string>'.
>               Type 'string | null' is not assignable to type 'string | Promise<string>'.
>                 Type 'null' is not assignable to type 'string | Promise<string>'.

...and something similar on the `new JwtConfigService(jwtOptions, authConfig),` line.

I'm running Angular 4.4.6, but I understand it's supposed to be backward compatible with 2, so I wonder if someone could tell me what I'm doing wrong?

**Comment by romicaiarca** [comment]
@jholovacs ,
add this line in import part of your file where you are using export function ``getJwtHttp(http: Http, options: RequestOptions)``

```js
import { Response  } from '@angular/http';
```

**Comment by jholovacs** [comment]
@romicaiarca I already had that.  My import section looks like this:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppModuleShared } from './app.module.shared';
import { AppComponent } from './components/app/app.component';
import { Http, RequestOptions, Response } from '@angular/http';
import { AuthConfig, AuthHttp } from 'angular2-jwt';
import { JwtConfigService, JwtHttp } from 'angular2-jwt-refresh';
```

**Comment by jholovacs** [comment]
I gave up on it.
