### ISSUE TITLE
Set the payload of refresh token request dynamically

### ISSUE THREAD

**Issue by emroussel** [leonardobazico/angular2-jwt-refresh#4]
The api I am working with requires the refresh token to be sent in the body. 

I tried using the payload in `jwtOptions` with static values and it works, but I will need to modify the refresh token when a user logs in and out.

Any idea if this is possible?

**Comment by leonardobazico** [comment]
Let's try to see if I understand what you want.

Do you want to change `jwtOptions.payload` dynamically to send the refresh token in the body?
The default is send through Authorization header, so I did expected for a function in `jwtOptions.payload`.

If you want test you can change [line 96](https://github.com/leonardobazico/angular2-jwt-refresh/blob/7b152c7db8aa9a8138c9c2fb465d78cf3b903605/src/angular2-jwt-refresh.ts)
from:  `body: this.refreshConfig.payload,` to some like that:
`body: typeof this.refreshConfig.payload === 'function' ? this.refreshConfig.payload() : this.refreshConfig.payload,`

If this works to you, feel free to send a pull request and don't forget to test it.

**Comment by emroussel** [comment]
Great, I will try it out.

**Comment by emroussel** [comment]
The changes work for a function that returns a value, but I am using Ionic Storage that returns a promise. Any suggestions on how to get it to work with a promise?

**Comment by leonardobazico** [comment]
Please check between lines 104 and 110, you need to do something like that.

**Comment by leonardobazico** [comment]
I believe that you can do something like that:

```typescript
  private getPayload(): Observable<any> {
    if (this.refreshConfig.payload instanceof Promise) {
      return Observable.fromPromise(this.refreshConfig.payload);
    }
    
    return Observable.of(this.refreshConfig.payload);
  }

  protected _refreshTheToken() {
    this.setRefreshing(true);
    
    
    let requestWithToken;
    let request = this.getPayload()
      .flatMap((payload) => {
        let options = new RequestOptions({
          body: payload,
          method: RequestMethod.Post,
          url: this.refreshConfig.endPoint
        });
      
        let req = new Request(this._mergeOptions(options, this._defOpts));
        let refreshToken: string | Promise<string> = this.refreshConfig.refreshTokenGetter();

        if (refreshToken instanceof Promise) {
          requestWithToken = Observable
            .fromPromise(refreshToken)
            .mergeMap((jwtToken: string) => this._requestWithToken(req, jwtToken));
        } else {
          requestWithToken = this._requestWithToken(req, refreshToken);
        }
      });

    return request
      .flatMap(requestWithToken)
      .flatMap((res: any) => {
        const tokenSetter = this.refreshConfig.tokenSetter(res);
        const onError = Observable.throw('Impossible to get new token');

        if (tokenSetter instanceof Promise) {
          return Observable
            .fromPromise(tokenSetter)
            .catch(() => {

              this.setRefreshing(false);
              this.emitRefreshToken();

              return onError;
            })
            .concatMap(() => Observable.of(res));
        }

        if (!tokenSetter) {
          return onError;
        }

        return Observable.of(res);
      })
      .concatMap((res) => {
        this.setRefreshing(false);
        this.emitRefreshToken();

        return Observable.of(res);
      })
      .catch((res: any) => {
        this.setRefreshing(false);
        this.emitRefreshToken();

        return Observable.of(res);
      });
  }
```

You can organize better than that too.

**Comment by leonardobazico** [comment]
@emroussel you can check now the version 0.1.0.

**Comment by emroussel** [comment]
Just updated, but the refresh request is still sent with a promise in the payload instead of the value.

Am I doing something wrong?
